import Config

# Configure your database
config :gitgame, GitGame.Repo,
  # The standard libpq variables, so CI can say postgres/postgres while a local Homebrew Postgres, which lets the
  # OS user in without a password, needs nothing set at all.
  username: System.get_env("PGUSER") || System.get_env("USER"),
  password: System.get_env("PGPASSWORD", "postgres"),
  hostname: System.get_env("PGHOST", "localhost"),
  database: "gitgame_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :gitgame, GitGameWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "2PxLCNA56Q/2F0LlisOYOYQD0DJGv2gaYskoPdiXZLviJAVmbUG+/9PIEm9DEK1m",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :gitgame, dev_routes: true

# Sessions over plain http on localhost (Safari won't keep a Secure cookie there), and writes from the Vite dev and
# preview servers, which proxy /api here (ADR-0005).
config :gitgame,
  secure_cookies: false,
  origins: ["http://localhost:5173", "http://localhost:4173"],
  # people reach the game at the Vite dev server, which proxies /api here; a development GitHub OAuth app's callback
  # URL is http://localhost:5173/api/auth/github/callback
  public_url: "http://localhost:5173"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
