defmodule GitGameWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :gitgame

  # The signed session cookie holds only a GitHub link in progress: its `state` and PKCE verifier, for the minutes
  # between leaving for GitHub and coming back (GitGameWeb.AuthController). Signed, so it can't be forged; Lax, so it
  # comes back with GitHub's redirect; Secure wherever there is TLS, as the session cookie is (ADR-0005).
  @session_options [
    store: :cookie,
    key: "_gitgame_key",
    signing_salt: "351MWJjO",
    same_site: "Lax",
    secure: Application.compile_env(:gitgame, :secure_cookies, true)
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :gitgame,
    gzip: not code_reloading?,
    only: GitGameWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :gitgame
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug GitGameWeb.Router
end
