// A small view in the shape the remote sends (server/lib/gitgame/games/view.ex), for tests. `over` replaces fields.
export function view(over = {}) {
  return {
    id: "g1",
    version: 3,
    day: 2,
    final_day: 12,
    day_length: "live",
    budget: 3,
    commands_allowed: true,
    release_at: 10,
    hand_limit: 10,
    max_ops: 4,
    default_strategy: "theirs",
    costs: {
      ops: {
        add: 1,
        commit: 1,
        push: 1,
        push_with_nothing_to_push: 0,
        pull: 1,
        pull_when_up_to_date: 0,
        pull_rebase: 2,
        resolve_by_hand_extra: 1,
        tag: 1,
        arm_trap: 0,
      },
      commands: { blame: 1, force: 1, reflog: 0, revert: 1 },
    },
    bots: ["bot"],
    deadline: "2026-09-29T20:00:00Z",
    incident: { id: "flaky_ci", name: "Flaky CI", text: "The next push rolls a die." },
    released: null,
    seats: ["ana", "bot"],
    sent_today: ["bot"],
    main: [
      { id: "16bb9f2", initial: true },
      {
        id: "53d8cce",
        author: "ana",
        message: "build: pin the base image",
        files: ["Dockerfile"],
        lines: 7,
        flipped: false,
        overwritten: false,
        reverted: false,
        revert_of: null,
      },
      {
        id: "15efd4d",
        author: "bot",
        message: "docs: <b>badge</b>",
        files: ["README.md"],
        lines: 4,
        flipped: true,
        bug: true,
        overwritten: false,
        reverted: false,
        revert_of: null,
      },
    ],
    players: {
      ana: {
        pointer: 2,
        behind: 1,
        hand: 3,
        staged: 0,
        to_push: 1,
        tokens: { merge: 1, grudges: 0, sins: 0, blame: 0, fixes: 0 },
        left: false,
      },
      bot: {
        pointer: 3,
        behind: 0,
        hand: 4,
        staged: 1,
        to_push: 0,
        tokens: { merge: 0, grudges: 0, sins: 1, blame: 3, fixes: 0 },
        left: false,
      },
    },
    scores: { ana: { total: 7 }, bot: { total: 1 } },
    days: [],
    today: [],
    you: {
      player: "ana",
      hand: [
        { id: "k1", kind: "commit", file: "auth.js", lines: 5, bug: false },
        { id: "k2", kind: "commit", file: "api.py", lines: 3, bug: true },
        { id: "k3", kind: "command", command: "force" },
      ],
      staged: [],
      local: [],
      armed: [],
      left: false,
    },
    ...over,
  };
}
